version: 2
updates:
- package-ecosystem: gitsubmodule
  directory: "/v-hacd"
  schedule:
    interval: monthly
    time: "13:00"
  open-pull-requests-limit: 10
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly
    time: "13:00"
  open-pull-requests-limit: 10
