[package]
name = "vhacd"
version = "0.1.0"
authors = ["Nathan Howell <nathan.d.howell@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.11"
ncollide3d = { version = "0.31.0", optional = true }
tracing = "0.1.21"
vhacd-sys = { path = "../vhacd-sys" }

[dev-dependencies]
env_logger = "0.9.0"
